version: '3.8'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}