export interface ResponseDto {
    id: number;
    jsonrpcd: string;
    result: {
        baseFeePerGas: string,
        difficulty: string,
        extraData: string,
        gasLimit: string,
        gasUsed: string,
        hash: string,
        logsBloom: string,
        miner: string,
        mixHash: string,
        nonce: string,
        number: string,
        parentHash: string,
        receiptsRoot: string,
        sha3Uncles: string,
        size: string,
        stateRoot: string,
        timestamp: string,
        totalDifficulty: string,
        transactions: {
            accessList: [],
            blockHash: string,
            blockNumber: string,
            chainId: string,
            from: string,
            gas: string,
            gasPrice: string,
            hash: string,
            input: string,
            maxFeePerGas: string,
            maxPriorityFeePerGas: string,
            nonce: string,
            r: string,
            s: string,
            to: string,
            transactionIndex: string,
            type: string,
            v: string,
            value: string,
        }[],
        transactionsRoot: string,
        uncles: [],
        withdrawals: {
            address: string,
            amount: string,
            index: string,
            validatorIndex: string,
        }[],
        withdrawalsRoot: string,
    }
}